name: Update change log on PR open

on:
  push:
    #branches:
    #  - develop

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Update changelog
        env:
          GITHUB_SERVER_URL: ${{ github.server_url }}
          GITHUB_API_URL: ${{ github.api_url }}
          GITHUB_ISSUES_URL: ${{ github.event.repository.issues_url }}

        run: |
          echo "Hi there from push, here is the context:"
          env | grep GITHUB