name: Update change log on PR open

on:
  push:
    #branches:
    #  - develop

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Update changelog
        env:
          GITHUB_CONTEXT: ${{ toJson(github)}}
        run: |
          echo "Hi there, here is the context:"
          echo "$GITHUB_CONTEXT"
          
          https://api.github.com/repos/cklellie/github-actions-test/issues/7