name: Update change log on PR open

on:
  pull_request:
    types: [opened]
    branches:
      - develop

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Update changelog
        run: |
          echo "Hi there" >> CHANGELOG.md
          echo "${{ github.event.pull_request.title }}" >> CHANGELOG.md
          echo "${{ github.event.pull_request.body }}" >> CHANGELOG.md
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add .
          git commit -m "Updated changelog."
          git push